/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ApiPublicTypebotWebhookRouteImport } from './routes/api/public/typebot-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTypebotWebhookRoute = ApiPublicTypebotWebhookRouteImport.update({
  id: '/api/public/typebot-webhook',
  path: '/api/public/typebot-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/importar': typeof ImportarRoute
  '/api/public/typebot-webhook': typeof ApiPublicTypebotWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/importar': typeof ImportarRoute
  '/api/public/typebot-webhook': typeof ApiPublicTypebotWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/importar': typeof ImportarRoute
  '/api/public/typebot-webhook': typeof ApiPublicTypebotWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/importar' | '/api/public/typebot-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/importar' | '/api/public/typebot-webhook'
  id: '__root__' | '/' | '/importar' | '/api/public/typebot-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportarRoute: typeof ImportarRoute
  ApiPublicTypebotWebhookRoute: typeof ApiPublicTypebotWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/typebot-webhook': {
      id: '/api/public/typebot-webhook'
      path: '/api/public/typebot-webhook'
      fullPath: '/api/public/typebot-webhook'
      preLoaderRoute: typeof ApiPublicTypebotWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportarRoute: ImportarRoute,
  ApiPublicTypebotWebhookRoute: ApiPublicTypebotWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
